# Generated by Django 2.2 on 2019-04-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=10)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlsp.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=10)),
                ('info', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlsp.Department')),
            ],
        ),
    ]
