# Generated by Django 2.2 on 2019-04-23 12:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dlsp', '0002_htmler_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='htmler',
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='value',
            field=tinymce.models.HTMLField(),
        ),
    ]
