# Generated by Django 2.2 on 2019-04-23 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dlsp', '0003_auto_20190423_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='info',
            field=tinymce.models.HTMLField(),
        ),
    ]
