# Generated by Django 2.2 on 2019-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlsp', '0004_auto_20190423_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
