# Generated by Django 2.2 on 2019-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlsp', '0005_auto_20190423_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/'),
        ),
    ]
